version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
    networks: [ 'atnetwork' ]
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    env_file:
      - ./.env
    ports:
      - 3333:3333
    networks:
      - 'atnetwork'
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    # ports:
    #   - 5432:5432
    expose:
      - 5432
    # volumes:
    #   - ./database:/var/lib/postgresql/data
    networks: [ 'atnetwork' ]
networks:
  atnetwork: {}
